"""
配置文件
"""

class Config:
    AKSHARE_DATA_SOURCE = 'em'
    
    MACD_DEFAULT_FAST = 12
    MACD_DEFAULT_SLOW = 26
    MACD_DEFAULT_SIGNAL = 9
    
    BB_DEFAULT_PERIOD = 20
    BB_DEFAULT_STD = 2.0
    
    RSI_DEFAULT_PERIOD = 14
    
    DEFAULT_COMMISSION = 0.0003
    DEFAULT_INITIAL_CASH = 100000.0
    
    SCREENING_MIN_DAYS = 60
    SCREENING_DEFAULT_LOOKBACK = 60
    SCREENING_VOLUME_RATIO = 2.0
    
    PLOT_DEFAULT_FIGSIZE = (14, 8)
    PLOT_DPI = 100
    
    BACKTEST_ANNUAL_TRADING_DAYS = 252
